from pathlib import Path
from fastapi import FastAPI
from secrets import randbelow
from subprocess import run, PIPE
from typing import Any, Dict, List
from mcp.server.fastmcp import FastMCP
from datetime import datetime, timezone
from fastapi.responses import JSONResponse
from fastapi.staticfiles import StaticFiles
from mcp.server.transport_security import TransportSecuritySettings
import os
import uuid
import kvapi
import asyncio
import freeipapi
import internetapi

# 1. Setup Configuration
HOST = "0.0.0.0"
PORT = 57790
ROOT = Path("./../root").resolve()
HIDD = Path("./../hidden").resolve()

Status = {
    "Status": "ok",
    "Services": [
        { "Service": "AI-webscripts", "ok": True },
        { "Service": "AI-Tools", "ok": True }
    ]
}

security = TransportSecuritySettings(
    enable_dns_rebinding_protection=True,
    allowed_hosts=[
        "localhost:*",
        "127.0.0.1:*",
        "192.168.100.123:*"
    ]
)

mcp = FastMCP("AI-Tools", transport_security=security)

def get_custom_error_page(code: int) -> str:
    file_map = {
        404: os.path.join(HIDD, "errors", "404.html"),
        403: os.path.join(HIDD, "errors", "403.html"),
        400: os.path.join(HIDD, "errors", "400.html"),
        503: os.path.join(HIDD, "errors", "503.html")
    }
    target_file = file_map.get(code)
    if target_file and os.path.exists(target_file):
        try:
            with open(target_file, "r", encoding="utf-8") as f:
                return f.read().format(PORT=PORT)
        except Exception as e:
            print(f"[SERVER] Error reading {code} page: {e}")
    return f"<h1>Error {code}</h1>"

# ----------------------------------------- #
# ----------------------------------------- #
# |       FastAPI/MCP Server Setup        | #
# ----------------------------------------- #
# ----------------------------------------- #



# MCP Tools
## Faker apis
@mcp.tool("generateFakeData")
def fakeDataSection_generateFakeData(count: int = 8) -> dict[str, object]:
    """
    Returns: Dict containing generated fake data for testing purposes.
    Args:
        count: number of records to generate (default 8)
    Description: Generates a small list of realistic-looking test records.
    """
    import random
    from datetime import datetime

    first_names = ["Alice", "Marcus", "Sofia", "Liam", "Zoe", "Noah", "Maya", "Ethan"]
    last_names = ["Nguyen", "Patel", "Martinez", "O'Connor", "Kim", "Brown", "Singh", "Williams"]
    cities = ["Seattle", "Austin", "San Diego", "Dublin", "Seoul", "London", "Mumbai", "Toronto"]

    records: list[dict] = []
    for i in range(count):
        fn = random.choice(first_names)
        ln = random.choice(last_names)
        name = f"{fn} {ln}"
        email_local = f"{fn}.{ln}".lower().replace("'", "")
        rec = {
            "id": randbelow(1000000),
            "uuid": str(uuid.uuid4()),
            "name": name,
            "email": f"{email_local}@example.com",
            "created_at": datetime.now(datetime.timezone.utc).replace(microsecond=0).isoformat() + "Z",
            "is_active": bool(randbelow(2)),
            "profile": {
                "age": 18 + randbelow(50),
                "city": random.choice(cities),
                "score": round(randbelow(10000) / 100.0, 1),
            },
        }
        records.append(rec)

    return {
        "message": "Fake data generated by fakeDataSection_generateFakeData",
        "count": len(records),
        "data": records,
    }

@mcp.tool("generateFakeUuid4")
def fakeDataSection_generateFakeUuid4(count: int = 8) -> dict[str, object]:
    """
    Returns: Dict containing generated fake UUID4 values for testing purposes.
    Args:
        count: number of UUID4 values to generate (default 8)
    Description: Generates a small list of random UUID4 values.
    """
    uuids: list[str] = [str(uuid.uuid4()) for _ in range(count)]
    return {
        "message": "Fake UUID4 values generated by fakeDataSection_generateFakeUuid4",
        "count": len(uuids),
        "data": uuids,
    }

@mcp.tool("generateFakeNames")
def fakeDataSection_generateFakeNames(count: int = 8) -> dict[str, object]:
    """
    Returns: Dict containing generated fake names for testing purposes.
    Args:
        count: number of names to generate (default 8)
    Description: Generates a small list of random names.
    """
    import random

    first_names = ["Alice", "Marcus", "Sofia", "Liam", "Zoe", "Noah", "Maya", "Ethan"]
    last_names = ["Nguyen", "Patel", "Martinez", "O'Connor", "Kim", "Brown", "Singh", "Williams"]

    names: list[str] = []
    for _ in range(count):
        fn = random.choice(first_names)
        ln = random.choice(last_names)
        names.append(f"{fn} {ln}")

    return {
        "message": "Fake names generated by fakeDataSection_generateFakeNames",
        "count": len(names),
        "data": names,
    }

## Process apis
@mcp.tool("runProcess")
def processSection_runProcess(pathtoexe: str, args: str = "") -> dict[str, object]:
    """
    Returns: Dict containing the result of running a process.
    Args:
        pathtoexe: Path to the executable to run.
        args: Arguments to pass to the executable (default empty).
    Description: Runs a process and captures its output and return code.
    """
    try:
        result = run([pathtoexe] + args.split(), stdout=PIPE, stderr=PIPE, text=True)
        return {
            "message": f"Process '{pathtoexe}' executed successfully.",
            "stdout": result.stdout,
            "stderr": result.stderr, 
        }
    except Exception as e:
        return {
            "message": f"Error executing process '{pathtoexe}': {e}",
            "returncode": -1,
            "stdout": "",
            "stderr": str(e),
        }

## Key-Value api
@mcp.tool("readKeysfromRecord")
def keyvalSection_readKeysfromRecord(recordName: str) -> Dict[str, Any]:
    """
    Return: Dict containing the keys from the specified record.
    Args:
        recordName: Name of the record to read keys from.
    Description: Reads keys from a record in the key-value store.
    """
    return kvapi.readKeysfromRecord(recordName)

@mcp.tool("addRecord")
def keyvalSection_addRecord(recordName: str) -> Dict[str, Any]:
    """
    Return: Dict containing the result of adding a record.
    Args:
        recordName: Name of the record to add.
    Description: Adds a new record to the key-value store.
    """
    return kvapi.addRecord(recordName)

@mcp.tool("delRecord")
def keyvalSection_delRecord(recordName: str) -> Dict[str, Any]:
    """
    Return: Dict containing the result of deleting a record.
    Args:
        recordName: Name of the record to delete.
    Description: Deletes a record from the key-value store.
    """
    return kvapi.delRecord(recordName)

@mcp.tool("listRecords")
def keyvalSection_listRecords() -> List[str]:
    """
    Return: List of record names in the key-value store.
    Description: Lists all records currently in the key-value store.
    """
    return kvapi.listRecords()

@mcp.tool("selectRecord")
def keyvalSection_selectRecord(recordName: str) -> Dict[str, Any]:
    """
    Return: Dict containing the result of selecting a record.
    Args:
        recordName: Name of the record to select.
    Description: Selects a record in the key-value store for subsequent key operations.
    """
    return kvapi.selectRecord(recordName)

@mcp.tool("listKeysfromRecord")
def keyvalSection_listKeysfromRecord() -> List[str]:
    """
    Return: List of keys from the selected record.
    Description: Lists the keys from the currently selected record in the key-value store.
    """
    return kvapi.listKeysfromRecord()

@mcp.tool("addKeytoRecord")
def keyvalSection_addKeytoRecord(key: str, value: Any) -> Dict[str, Any]:
    """
    Return: Dict containing the result of adding a key to the selected record.
    Args:
        key: Key to add to the selected record.
        value: Value to associate with the key in the selected record.
    Description: Adds a key-value pair to the currently selected record in the key-value store.
    """
    return kvapi.addKeytoRecord(key, value)

@mcp.tool("delKeyfromRecord")
def keyvalSection_delKeyfromRecord(key: str) -> Dict[str, Any]:
    """
    Return: Dict containing the result of deleting a key from the selected record.
    Args:
        key: Key to delete from the selected record.
    Description: Deletes a key from the currently selected record in the key-value store.
    """
    return kvapi.delKeyfromRecord(key)

@mcp.tool("readKeyfromRecord")
def keyvalSection_readKeyfromRecord(key: str) -> Dict[str, Any]:
    """
    Return: Dict containing the value of the specified key from the selected record.
    Args:
        key: Key to read from the selected record.
    Description: Reads a key from the currently selected record in the key-value store and returns its value.
    """
    return kvapi.readKeyfromRecord(key)

@mcp.tool("writeKeytoRecord")
def keyvalSection_writeKeytoRecord(key: str, value: Any) -> Dict[str, Any]:
    """
    Return: Dict containing the result of writing a key to the selected record.
    Args:
        key: Key to write to the selected record.
        value: Value to associate with the key in the selected record.
    Description: Writes a key-value pair to the currently selected record in the key-value store, updating it if it already exists.
    """
    return kvapi.writeKeytoRecord(key, value)

## FreeIPAPI
@mcp.tool("getIPinfo")
def FreeIPAPI_getIPinfo(ip: str) -> Dict[str, Any]:
    """
    Returns: Dict containing information about the specified IP address.
    Args:
        ip: IP address to retrieve information for.
    Description: Fetches information about an IP address from the currently selected FreeIPAPI server.
    """
    return freeipapi.getIPInfo(ip)

@mcp.tool("selectServer")
def FreeIPAPI_selectServer(server: str) -> Dict[str, Any]:
    """
    Returns: Dict containing the result of selecting a FreeIPAPI server.
    Args:
        server: Country code of the FreeIPAPI server to select (e.g., "US", "DE", "SGP", "AU").
    Description: Selects a FreeIPAPI server based on the provided country code for subsequent IP information queries.
    """
    return freeipapi.selectServer(server)

@mcp.tool("listServers")
def FreeIPAPI_listServers() -> List[Dict[str, str]]:
    """
    Returns: List of available FreeIPAPI servers with their country codes and URLs.
    Args: None
    Description: Lists all available FreeIPAPI servers that can be selected for IP information queries.
    """
    return freeipapi.allservers

@mcp.tool("getSelectedServer")
def FreeIPAPI_getSelectedServer() -> Dict[str, str]:
    """
    Returns: Dict containing information about the currently selected FreeIPAPI server.
    Args: None
    Description: Retrieves information about the FreeIPAPI server that is currently selected for IP information queries.
    """
    return freeipapi.selectedServer

@mcp.tool("summarizeIPinfo")
def FreeIPAPI_summarizeIPinfo(ip: str) -> Dict[str, Any]:
    """
    Returns: Dict containing a summary of the information about the specified IP address.
    Args:
        ip: IP address to summarize information for.
    Description: Provides a concise summary of the key information about the IP address, including location and any notable details.
    """
    return f"Summarize the following output: {freeipapi.getIPInfo(ip)}.\nProvide a concise summary of the key information about the IP address, including location and any notable details."


## Internet API
@mcp.tool("clearBrowserHistory")
def browserApi_clearBrowserHistory() -> str:
    """
    Returns: string for confirmation
    Args: None
    Description: Clears recently visited history and resets urlbar to google.com
    """
    return internetapi.clearVisitHistory()

@mcp.tool("typeInUrlBar")
async def browserApi_typeInUrlBar(url: str, params: dict | str | None = None, headers: dict = {}) -> str:
    """
    Returns: string of confirmation
    Args:
        url: str = the url
        params: dict | str | None = the query params
        headers: dict = headers to be given
    Description: types in the url into urlbar
    """

    return await internetapi.selectUrlfromUrlBar(url, params, headers)

@mcp.tool("gotoUrlInUrlBar")
async def browserApi_gotoUrlInUrlBar(method: str = "GET", 
                         content: str = "None: Via MCP SERVER",
                         headers: dict = {}, 
                         caching: bool = True,
                         errinvalid_verb: bool = True,
                         markdownizer: bool = True) -> str:
    """
    Return: string of confirmation
    Args:
        method: str = The method to request:
            GET, POST, PUT, PATCH, HEAD
        content: str = Required if using POST, PUT, PATCH for the body
        headers: dict = headers to put in the request
        caching: bool = Weather to cache the response or not
        errinvalid_verb = if using invalid verb, send error or use default GET
    """
    
    resp = await internetapi.gotoUrlInUrlBar(method=method, content=content,
                                       headers=headers, caching=caching,
                                       errinvalid_verb=errinvalid_verb)
    if markdownizer:
        return internetapi.convertHtmlToMarkdown
    return resp

@mcp.tool("convertHtmlToMarkdown")
def browserApi_convertHtmlToMarkdown(html: str) -> str:
    """
    Returns: string thats converted into md
    Args:
        html: str = string version of html
    Description: Converts html to markdown
    """

    return internetapi.convertHtmlToMarkdown(html)



# --------------------------------------

app = FastAPI(title="AI-Webscripts")
app.mount("/mcp", mcp.sse_app())

@app.get("/status")
async def get_status():
    return JSONResponse(content=Status)

if ROOT.exists():
    app.mount("/", StaticFiles(directory=ROOT, html=True), name="root")


def main() -> None:
    import uvicorn
    print(f"Starting AI-Webscripts on http://{HOST}:{PORT}/")
    print(f"MCP Endpoint available at http://{HOST}:{PORT}/mcp")
    
    uvicorn.run(app, host=HOST, port=PORT, log_config=None)

if __name__ == "__main__":
    main()